version: "3.9"
   
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sr_public_webapp_container
    volumes:
      - ../:/container_project_stuff
      - ../logs:/container_project_stuff/logs
      - ../example_data_source:/container_project_stuff/example_data_source
      - .:/container_project_stuff/sr_public_webapp_project
    ports:
      - "8000:8000"

    environment:
      - SR_PUBWEBAPP__ENV_SETTINGS_PATH=config/settings_localdev_env.sh

    env_file: ./config/settings_localdev_env.sh

    # command: /bin/bash -c "python manage.py runserver 0.0.0.0:8000"

    # command: /bin/bash -c "if [ ! -f /container_project_stuff/example_data_source/foo.txt ]; then echo 'foo' > /container_project_stuff/example_data_source/foo.txt; fi; python manage.py runserver 0.0.0.0:8000"

    # command: |
    #   /bin/bash -c "
    #   if [ ! -f /container_project_stuff/example_data_source/foo.txt ]; then 
    #     echo 'foo' > /container_project_stuff/example_data_source/foo.txt; 
    #   fi; 
    #   python manage.py runserver 0.0.0.0:8000"

    command: |
      /bin/bash -c "
      if [ ! -f /container_project_stuff/example_data_source/people.json ]; then 
        echo '[{\"first_name\": \"emma\", \"last_name\": \"goldman\"},{\"first_name\": \"frida\", \"last_name\": \"kahlo\"},{\"first_name\": \"eleanor\", \"last_name\": \"roosevelt\"}]' > /container_project_stuff/example_data_source/people.json;
      fi; 
      python manage.py runserver 0.0.0.0:8000"
