version: "3.8"
## Specifies the version of the Compose file-format; must be compatible with the version of the Docker Engine.
## See: https://docs.docker.com/compose/compose-file/compose-versioning/
   
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sr_public_webapp_container
    volumes:
      - ../:/container_project_stuff                                          # maps parent-directory on the host to '/container_project_stuff' in the Docker container.
      - ../logs:/container_project_stuff/logs                                 # maps the 'logs' sub-directory from the parent-directory on the host to '/container_project_stuff/logs' in the Docker container.
      - ../example_data_source:/container_project_stuff/example_data_source   # maps the 'example_data_source' sub-directory from the parent-directory on the host to '/container_project_stuff/example_data_source' in the Docker container.
      - .:/container_project_stuff/sr_public_webapp_project                   # maps the current-directory on the host to '/container_project_stuff/sr_public_webapp_project' in the Docker container.
    ports:
      - "8000:8000"                                                           # maps port 8000 on the host to port 8000 in the Docker container.

    environment:
      - SR_PUBWEBAPP__ENV_SETTINGS_PATH=config/requirements_base.in
      # - SR_PUBWEBAPP__ENV_SETTINGS_PATH=config/settings_localdev_env.sh

    env_file: ./config/settings_localdev_env.sh

    ## The vertical pipe "|"" in YAML is used to indicate a literal block of text; allowing the different commands to be written on separate lines.
    ## Starts a new bash shell and runs the following two commands: the people.json if-check command -- and then runs the runserver command.
    command: |
      /bin/bash -c "
      if [ ! -f /container_project_stuff/example_data_source/people.json ]; then 
        echo '[{\"first_name\": \"emma\", \"last_name\": \"goldman\"},{\"first_name\": \"frida\", \"last_name\": \"kahlo\"},{\"first_name\": \"eleanor\", \"last_name\": \"roosevelt\"}]' > /container_project_stuff/example_data_source/people.json;
      fi; 
      python manage.py runserver 0.0.0.0:8000"
